In [4]:
import warnings
import numpy as np
import pandas as pd
# warning 출력 ignore
warnings.filterwarnings(action='ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler

# 0401 scaler reshape Error

In [6]:
# Raw Data Set Loading
df = pd.read_csv('./data/ozone.csv')

In [7]:
df.head()

Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5

In [9]:
df_01 = df.drop(['Month','Day'], axis=1)
df_01

Ozone  Solar.R  Wind  Temp
0     41.0    190.0   7.4    67
1     36.0    118.0   8.0    72
2     12.0    149.0  12.6    74
3     18.0    313.0  11.5    62
4      NaN      NaN  14.3    56
..     ...      ...   ...   ...
148   30.0    193.0   6.9    70
149    NaN    145.0  13.2    77
150   14.0    191.0  14.3    75
151   18.0    131.0   8.0    76
152   20.0    223.0  11.5    68

[153 rows x 4 columns]

In [10]:
scaler = MinMaxScaler()
scaler.fit(df_01).transform(df_01)

array([[0.23952096, 0.55963303, 0.3       , 0.26829268],
       [0.20958084, 0.33944954, 0.33157895, 0.3902439 ],
       [0.06586826, 0.43425076, 0.57368421, 0.43902439],
       [0.10179641, 0.93577982, 0.51578947, 0.14634146],
       [       nan,        nan, 0.66315789, 0.        ],
       [0.16167665,        nan, 0.69473684, 0.24390244],
       [0.13173653, 0.89296636, 0.36315789, 0.2195122 ],
       [0.10778443, 0.28134557, 0.63684211, 0.07317073],
       [0.04191617, 0.03669725, 0.96842105, 0.12195122],
       [       nan, 0.57186544, 0.36315789, 0.31707317],
       [0.03592814,        nan, 0.27368421, 0.43902439],
       [0.08982036, 0.76146789, 0.42105263, 0.31707317],
       [0.05988024, 0.86544343, 0.39473684, 0.24390244],
       [0.07784431, 0.81651376, 0.48421053, 0.29268293],
       [0.10179641, 0.17737003, 0.60526316, 0.04878049],
       [0.07784431, 1.        , 0.51578947, 0.19512195],
       [0.19760479, 0.91743119, 0.54210526, 0.24390244],
       [0.02994012, 0.21712538,

In [15]:
scaler.fit(df_01['Ozone'].values.reshape(-1,1)).transform(df_01['Ozone'].values.reshape(-1,1))

array([[0.23952096],
       [0.20958084],
       [0.06586826],
       [0.10179641],
       [       nan],
       [0.16167665],
       [0.13173653],
       [0.10778443],
       [0.04191617],
       [       nan],
       [0.03592814],
       [0.08982036],
       [0.05988024],
       [0.07784431],
       [0.10179641],
       [0.07784431],
       [0.19760479],
       [0.02994012],
       [0.17365269],
       [0.05988024],
       [0.        ],
       [0.05988024],
       [0.01796407],
       [0.18562874],
       [       nan],
       [       nan],
       [       nan],
       [0.13173653],
       [0.26347305],
       [0.68263473],
       [0.21556886],
       [       nan],
       [       nan],
       [       nan],
       [       nan],
       [       nan],
       [       nan],
       [0.16766467],
       [       nan],
       [0.41916168],
       [0.22754491],
       [       nan],
       [       nan],
       [0.13173653],
       [       nan],
       [       nan],
       [0.11976048],
       [0.215

In [23]:
predict = np.array([[41, 190, 7.4, 67]])
scaler_x = scaler.fit(df_01)
scaled_predict = scaler_x.transform(predict)
scaled_predict

array([[0.23952096, 0.55963303, 0.3       , 0.26829268]])

In [18]:
df_test = df_01.iloc[:,1:]

scaler.fit(df_01.iloc[:,1:]).transform(df_01.iloc[:,1:])

array([[0.55963303, 0.3       , 0.26829268],
       [0.33944954, 0.33157895, 0.3902439 ],
       [0.43425076, 0.57368421, 0.43902439],
       [0.93577982, 0.51578947, 0.14634146],
       [       nan, 0.66315789, 0.        ],
       [       nan, 0.69473684, 0.24390244],
       [0.89296636, 0.36315789, 0.2195122 ],
       [0.28134557, 0.63684211, 0.07317073],
       [0.03669725, 0.96842105, 0.12195122],
       [0.57186544, 0.36315789, 0.31707317],
       [       nan, 0.27368421, 0.43902439],
       [0.76146789, 0.42105263, 0.31707317],
       [0.86544343, 0.39473684, 0.24390244],
       [0.81651376, 0.48421053, 0.29268293],
       [0.17737003, 0.60526316, 0.04878049],
       [1.        , 0.51578947, 0.19512195],
       [0.91743119, 0.54210526, 0.24390244],
       [0.21712538, 0.87894737, 0.02439024],
       [0.96330275, 0.51578947, 0.29268293],
       [0.11314985, 0.42105263, 0.14634146],
       [0.0030581 , 0.42105263, 0.07317073],
       [0.95718654, 0.78421053, 0.41463415],
       [0.

In [22]:
# predict = np.array([[190, 7.4, 67]])
predict = np.array([[150.0, 10.0, 80.0]])

scaler_x = scaler.fit(df_01.iloc[:,1:])
scaled_predict = scaler_x.transform(predict)
scaled_predict

array([[0.43730887, 0.43684211, 0.58536585]])

In [25]:
np.log1p(df_01)

Ozone   Solar.R      Wind      Temp
0    3.737670  5.252273  2.128232  4.219508
1    3.610918  4.779123  2.197225  4.290459
2    2.564949  5.010635  2.610070  4.317488
3    2.944439  5.749393  2.525729  4.143135
4         NaN       NaN  2.727853  4.043051
..        ...       ...       ...       ...
148  3.433987  5.267858  2.066863  4.262680
149       NaN  4.983607  2.653242  4.356709
150  2.708050  5.257495  2.727853  4.330733
151  2.944439  4.882802  2.197225  4.343805
152  3.044522  5.411646  2.525729  4.234107

[153 rows x 4 columns]